config/routes.rb
Rails.application.routes.draw do

 root 'restaurants#index'
 resources :restaurants do
   resources :reservations, only: [:new,:show,:create,:destroy]
 end
 resources :users, only: [:new,:create,:show,:destroy]

 resources :sessions, only: [:new,:create,:destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  validate :max_party_size
  validate :check_hourly_capacity


  def max_party_size
    if self.party_size > 10
      errors.add(:base, "Sorry, party size cannot be more than 10 people!")
    end
  end

  def check_hourly_capacity

    other_people = Reservation.where(restaurant_id:restaurant_id, time:time).sum(:party_size)

    if other_people + party_size > Restaurant.first.capacity
      errors.add(:base, "Sorry, restaurant has reached capacity!")
    end

    # restaurant.available?(party_size, time)
  end


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations

  validates :name, :address, presence: true

  mount_uploader :image, ImageUploader

  def hours_open
    (open...close).to_a
  end

  # def available?(party_size, time)
  #   reservations_for_time = reservations.where(time: time)
  #   reservations_for_time.sum(:party_size) + party_size <= capacity
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations

  validates :name,:email, presence: true

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_restaurant


  def create

    @reservation = @restaurant.reservations.build(reservation_params)

    # @reservation = Reservation.new(reservation_params)
    # @reservation.restaurant = @restaurant

    @reservation.user = current_user
    if @reservation.save
      redirect_to user_path(current_user), notice: "Reservation created successfully"
    else
      render "restaurants/show"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to :back
  end

private
 def reservation_params
  params.require(:reservation).permit(:time,:party_size)
 end

 def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
 end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
     redirect_to restaurants_path
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

private
  def restaurant_params
    params.require(:restaurant).permit(:name,:address,:website_url,:image,:capacity,:description,:open,:close)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :back, notice: "Logged out!"

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_path, notice: "Signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations

  end

  def destroy
    @user = User.find(user_params)
    @user.destroy
    redirect_to users_path
  end

private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_time(h)
    if h > 12
      (h-12).to_s + ":00 PM"
    elsif h == 12
      h.to_s + ":00 PM"
    else
      h.to_s + ":00 AM"
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  # def link_to_photo(photo)
  #   link_to image_tag(photo), photo_path(photo)
  # end


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SeatYourself</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>



  <nav class="navbar navbar-default navbar-fixed-top navpad">

    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SeatYourself</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li class="hidden">
                  <a href="#page-top"></a>
              </li>
              <li class="page-scroll">
                  <a href="/#portfolio">Restaurants</a>
              </li>
              <li class="page-scroll">
                  <a href="/#about">About</a>
              </li>
              <li class="page-scroll">
                  <a href="#contact">Contact</a>
              </li>
              <li class="page-scroll">
                    <div class="user-nav">
                      <% if current_user %>
                      <div class="user-nav-logged">
                          <%= link_to user_path(current_user) do %>
                            <%= image_tag current_user.avatar.url(:thumb),:class => 'user-thumb-image'%>
                            <%= current_user.name %>
                            <% end %>
                          <%= link_to "Log out", session_path("current"), :method => :delete %>
                      <% else %>
                          <%= link_to "Log in", new_session_path %> / <%= link_to "Sign up", new_user_path %>
                        <% end %>
                      </div>
                    </div>
              </li>

          </ul>
      </div>
        <!-- /.navbar-collapse -->
    </div>
        <!-- /.container-fluid -->

      <% if flash[:notice] %>
        <p class="flash-message"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
        <p class="flash-message"><%= flash[:alert] %></p>
      <% end %>

  </nav>


  <%= yield %>

  <!-- Footer -->
    <footer class="text-center" id ="contact">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>3481 Melrose Place<br>Beverly Hills, ON 90210<br>Canada</p>

                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Contact Us</h3>
                        <p>SeatYourself is open to any feedback. Please contact us at contact@seatyourself.com</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Seatyourself 2014
                    </div>
                </div>
            </div>
        </div>
    </footer>



</body>
</html>

app/views/restaurants/index.html.erb
<!-- Gif Cover Section -->
<div class="jumbotron headerwrap">
  <h1 class="align covercolor1">Welcome to Seatyourself!</h1>
  <p class="align covercolor">The number #1 site to reserve restaurant tables</p>
  <p class="align"><a class="btn btn-primary btn-lg" href="#about" role="button">Learn more</a></p>
</div>

<!-- New Restaurant portfolio section -->

<section id="portfolio">
    <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2>Restaurants</h2>
              <hr class="star-primary">
          </div>
      </div>
      <div class="row">
        <% @restaurants.each do |restaurant| %>
          <div class="col-sm-4 portfolio-item">

            <%= link_to restaurant_path(restaurant), :class => "portfolio-link" do %>
              <div class="caption">
                <div class="caption-content">
                    <i class="fa fa-search-plus fa-3x"></i>
                </div>
              </div>
              <img src="https://upload.wikimedia.org/wikipedia/commons/4/42/Resturant.jpg" alt="" class="img-responsive">
            <% end %>
            <div class="restaurant-index-test">
              <%= link_to restaurant.name,restaurant_path(restaurant), :class => "restaurant-index"%>
            </div>
          </div>
        <% end %>
   <!--      <p class="align"><a class="btn btn-primary btn-lg" href="#" role="button">Add Restaurant</a></p> -->
      </div>
    </div>
</section>

  <!-- About Section -->
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <p>Quisque nisi ex, egestas vel tempus at, tempor eu diam. Pellentesque esteines ullamcorper faucibus ornare. Maecenai posuere lacus eu luctus tincidunt. Duis euismod augue eu sem tristique portai. Nam placerat aliquet dolor, in congueit dui fermentum et nueve doz trec domt.</p>
            </div>
            <div class="col-lg-4">
                <p>Nulla a libero ac sapien finibus hasddd malesuada. Suspendisse in lacinia don risus. Cras id dui lobortis, bibendum itt nibh eu, vestibulum purus. Maecenass sit amet consequat nisi. Maecenas quii pellentesque ipsum.Nam placerat jogsi aliquet dolor, in congue dui fermentum.</p>
            </div>
        </div>
    </div>
</section>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= form_for @restaurant, html: { multipart: true } do |f| %>
  <% if @restaurant.errors.any? %>
      <h2><%= pluralize(@restaurant.errors.count,"error") %> prohibited this restaurant from being saved:</h2>
      <ul>
          <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :website_url %>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <p>OR</p>
  <div class="field">
    <label>My Avatar URL:</label>
    <%= image_tag(@restaurant.image_url) if @restaurant.image? %>
    <%= f.text_field :remote_image_url %>
  </div>
  <%= f.submit %>
<% end %>

<%= link_to "Back to all restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<% if current_user %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="restaurant-main">

  <img src="https://upload.wikimedia.org/wikipedia/commons/4/42/Resturant.jpg" alt="" class="restaurant-image">
  <div class="restaurant-labels">
  <h1><%= @restaurant.name %></h1>
  <p class="restaurant-tag"><%= @restaurant.tag %></p>
  <div><%= @restaurant.address %></div>
  <div class="restaurant-description"><%= @restaurant.description %></div>
  <%= link_to "Website", @restaurant.website_url %>
  </div>
</div>

  <h3 class="align reserve-heading">Reservation Times</h3>
  <%= form_for([@restaurant, @reservation], :html => {:class => 'reserve-form'}) do |f| %>
      <div class="times reserve-times">
        <% @restaurant.hours_open.each do |h| %>
          <%= f.radio_button :time, h %>
          <%= f.label "time_#{h}", new_time(h), class: "reserve" %>
        <% end %>
      </div>
      <div class="reserve-party align">
      <%= f.label :party_size,'Please enter party size' %>
      <%= f.text_field :party_size %>
      </div>
      <div class="reserve-party align">
      <%= f.submit %>
      </div>
  <% end %>


<div class="align restaurant-back">
<%= link_to "Back to Main Page", restaurants_path %>
</div>

app/views/users/new.html.erb
<div class="user-padding">
  <h1>Sign up!</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <h2><%= pluralize(@user.errors.count,"error") %> prohibited from sign up!</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
        <% end %>
      </ul>
    <%end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>
      <%= f.submit%>
  <% end %>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/users/show.html.erb
<% if current_user %>
  <div class="user-profile align">
      <h3 class="user-profile-heading">Profile</h3>
      <%= image_tag @user.avatar.url, :class => "user-profile-image" %>
    <div class="user-profile-label">
    <h5>Name: <%= @user.name %></h5>
    <h5>Email: <%= @user.email %></h5>
    <h5>Joined On: <%= @user.created_at.strftime("%B %d, %Y") %></h5>
    </div>
  </div>
  <hr/>

  <h3 class="align">Reservations</h3>

  <div class="user-reservation-box">
    <% @user.reservations.each do |reservation| %>
      <div class="user-reservation align">
        <p>Restaurant: <%= reservation.restaurant.name %></p>
        <p>Reserved Time: <%= reservation.time%></p>
        <p>Party Size: <%= reservation.party_size %></p>
        <p>Added on: <%= reservation.created_at.strftime("%B %d, %Y") %></p>

        <%= link_to "Remove Reservation", restaurant_reservation_path(reservation.restaurant_id, reservation), method: :delete %>
      </div>
    <% end %>
  </div>
<% end %>